services:
  postgres:
    image: postgres:16
    container_name: local_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "9090:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=*"]

  mongo:
    image: mongo:6
    container_name: local_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: test_user
      MONGO_INITDB_ROOT_PASSWORD: test_password
    ports:
      - "9091:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: local_redis
    restart: unless-stopped
    ports:
      - "9092:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--bind", "0.0.0.0", "--protected-mode", "no"]

volumes:
  postgres_data:
  mongo_data:
  redis_data:
